### PR TITLE
Issue 170

### PR DESCRIPTION
**Pull request by n3pjk**
Besides the custom themes and plugins, I noticed that there's no check if the user is managed locally or not. Our desktops are joined to a domain and managed with PBIS. I put the defaults into a default dictionary to simplifies conditionals. I cleaned up the jinja scripts in the template and moved the user loop up to main, simplifying the install code.

### CODE REVIEW

**Comment by n3pjk** [comment]
I've also made the .zshrc jinja template able to be overridden.

**Comment by freemanjp** [comment]
Hi @n3pjk. I appreciate the PR (you clearly put a lot of work into it), but unfortunately, I've decided to depreciate this Ansible role. It's been years since I've used this role myself and I no longer have time to maintain it.

I've moved on to using a Zsh Plugin manager ([zimfw](https://github.com/zimfw/zimfw)) and a custom dotfile repo (https://code.visualstudio.com/docs/devcontainers/containers#_personalizing-with-dotfile-repositories).

You're welcome to fork this role, but the tests are broken due to incompatible Python dependency changes. I've been moving my roles to use [tox](https://tox.wiki/) for testing (in place of my Molecule Wrapper script) and freezing all the dependency versions, but this role hasn't been updated.

**Comment by n3pjk** [comment]
Sounds good. The role is useful for automated deployments in an enterprise. My desktop happened to be fairly customized. I wanted to give back and would be interested in taking over maintainer responsibilities if you'd like. There's more updates to be made due to zsh-newuser-install, compinit, and more.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by freemanjp** [comment]
@n3pjk, unfortunately, given this Ansible role is under my company `gantsign` namespace, I can't make someone else maintainer (it'd expose me to legal risk if there were any issues). There's also no way of transferring an Ansible Galaxy role to another namespace. I would suggest that you fork the role (it is MIT licensed), and update the `README.md` to make it clear it's no longer a role maintained by me or GantSign. I could then update the `README.md` in my repo to link to your fork.

**Pull request closed without merging**
