### PR TITLE
allow to specify custom configuration

### PR DESCRIPTION
**Pull request by n0emis**

### CODE REVIEW

**Comment by tutunak** [comment]
@n0emis do you plan to fix it?

**Comment by n0emis** [comment]
> @n0emis do you plan to fix it?

Plan to fix what?

**Comment by tutunak** [comment]
@n0emis test was failed.

**Comment by n0emis** [comment]
That error seems like something I did not cause. Could you re-run the tests please?

**Comment by tutunak** [comment]
Unfortunately not, maybe @freemanjp could help us.

**Comment by freemanjp** [comment]
@n0emis thanks for the pull request, but unfortunately I won't be accepting this change. In my experience, once you need to customize the `~/.zshrc` it quickly becomes difficult to maintain without a Zsh Plugin manager such as [Antigen](http://antigen.sharats.me). Which is why I created an Ansible role for Antigen ([gantsign.antigen](https://github.com/gantsign/ansible_role_antigen)), with that you can install Oh My Zsh and configure it with all the custom configuration you need.

**Pull request closed without merging**
